### ISSUE TITLE
Merge to Unitful?

### ISSUE THREAD

**Issue by mo8it** [MasonProtter/NaturallyUnitful.jl#10]
People from Unitful seem to be open for a merge: https://github.com/PainterQubits/Unitful.jl/issues/480
Are you OK with that? This would join forces and introduce your awesome functions for natural units to people not knowing about NaturallyUnitful.
I would then try to prepare a merge request which you can review.

**Comment by mo8it** [comment]
The pull request would be ready if you agree:
https://github.com/Mo8it/Unitful.jl/tree/feature/natural_units

I did include the functionality, tests and docs. Please check everything and do some changes/improvements if you want.

I did also mention your name as the original author:
https://github.com/Mo8it/Unitful.jl/blob/0b25fc0f11e0216d487552777709d57266d3dafb/src/natural_units.jl#L1

**Comment by MasonProtter** [comment]
Yes, that’s totally fine. I have a feeling that they wouldn’t want this in the repo, at least not without changing the names of the functions, but feel free to try and get it merged!

**Comment by mo8it** [comment]
Yeah, did not want to merge it. But I did mention NaturallyUnitful.jl in the README.
