### ISSUE TITLE
Differing constants between Unitful.jl and NaturallyUnitful.jl

### ISSUE THREAD

**Issue by sostock** [MasonProtter/NaturallyUnitful.jl#11]
This package defines the following constants:
https://github.com/MasonProtter/NaturallyUnitful.jl/blob/165f55919cc3bffe22c5c8ac891c2065ed6e4817/src/NaturallyUnitful.jl#L6-L10
Some of these are already defined in Unitful.jl, although with slightly different values:
```julia
julia> Unitful.ħ
1.0545718176461565e-34 J s

julia> NaturallyUnitful.ħ
1.0545718e-34 kg m^2 s^-1

julia> (Unitful.ħ - NaturallyUnitful.ħ)/Unitful.ħ |> NoUnits # relative difference between the two values
1.6733005915006143e-8
```
Is there a reason for this? Does the community that uses natural units prefer these values over the CODATA recommended values used by Unitful.jl?

If there is no reason for the different values, I would suggest to just import the values from Unitful.jl where possible, to avoid possible confusion. Note that this is not possible in the case of `c`, since `Unitful.c` is a unit and `NaturallyUnitful.c` is a quantity (equal to `1 * Unitful.c`).

**Comment by MasonProtter** [comment]
No, there was no reason for this, thanks for bringing it up.  Fixed in https://github.com/MasonProtter/NaturallyUnitful.jl/commit/81ef2ba87db6b38339501cbfabbec7e3143047bb
