### ISSUE TITLE
Tests broken by Unitful CODATA update

### ISSUE THREAD

**Issue by c42f** [MasonProtter/NaturallyUnitful.jl#5]
Unitful updated constants to CODATA 2018; I think this has broken the tests in this package.

See https://github.com/PainterQubits/Unitful.jl/pull/235

**Comment by MasonProtter** [comment]
Thanks for the heads up! Will fix now.

**Comment by c42f** [comment]
Awesome :-D

**Comment by MasonProtter** [comment]
Fixed on latest tag

@JuliaRegistrator register()

**Comment by MasonProtter** [comment]
Oops

@JuliaRegistrator register()
